### ISSUE TITLE
Redirect to detail view after creation

### ISSUE THREAD

**Issue by TIIUNDER** [neeedo/neeedo-android#19]
Redirect to single view after creation of demands and offers

**Comment by stephanlindauer** [comment]
why not redirect to the list?

**Comment by TIIUNDER** [comment]
It should be like this:

I create a demand → get to the correct detail view and can right away swipe through my matched offers

**Comment by GammaG** [comment]
I for that too, this can prevent having inconsistent data. Because of the api does not direct include the created offer to the list, so the information might isn't available and local cache can be wrong. 
I currently add the created object to the cache in the model und the getter methode to the server just add the other ones. So it isn't twice in the list. Don't know if that's nice or not.

**Comment by GammaG** [comment]
We change this now? If we do I need to change some append conditions.

**Comment by stephanlindauer** [comment]
@TIIUNDER @GammaG 
lets not do this. discuss! ;)

**Comment by TIIUNDER** [comment]
Yes, let's skip this. To much work for a small feature and high potential for new bugs ;-)

**Comment by GammaG** [comment]
jop would have a lot of sideeffects ^^
